#!/bin/bash
#SBATCH --job-name=ML_train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task 4
#SBATCH --mincpus=4
#SBATCH --time=1-20:00:00
#SBATCH --mem=40gb
#SBATCH -p q32g
#SBATCH --gres gpu


source /home/${USER}/.bashrc
conda activate tf_gpu

#srun python3 -u /home/au567859/DataHandling/notebooks/22-02-16_final_model_all_vels_and_heat_pr0025.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-02-21_final_model_all_vels_and_heat_pr071_padding.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-02-17_predict_new_models.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-20_Predicting_mix.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-04-27_Test_using_pertubations.py
srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus50_uvwT_pr1.py

#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-17_Mixture_of_Experts_linear_all4_15.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-17_Mixture_of_Experts_linear_all4_50.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-17_Mixture_of_Experts_linear_all4_75.py

#srun python3 -u /home/au567859/DataHandling/notebooks/22-06-02_final_model_padding8_yplus15_uvw_dudy.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-06-02_final_model_padding8_yplus30_uvw_dudy.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-06-02_final_model_padding8_yplus50_uvw_dudy.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-06-02_final_model_padding8_yplus75_uvw_dudy.py

#srun python3 -u /home/au567859/DataHandling/notebooks/22-06-02_final_model_padding8_yplus50_uvw_TauWallNormalizedInput.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-05-02_Mixture_of_Experts_alternative_linear_1x1conv_4Pr_OnEndPred.py

#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus75_uvwT_pr0025.py
#srun python3 -u /home/au567859/DataHandling/notebooks/test3.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus75_uvwT_pr02.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus75_uvw_pr02.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus75_uvw_pr071.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus15_uvw_pr1.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus15_uvwT_pr1.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus30_uvw_pr1.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus50_uvwT_pr1.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus50_uvw_pr1.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-08_final_model_padding8_yplus30_uvwT_pr1.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-11_transfer_learning.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-23_final_model_padding8_yplus30_uvwT_pr071_IMD_15.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-15_final_model_padding8_yplus50_uvwT_pr071_and_y_plus50uvwT.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-17_Mixture_of_Experts_linear.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-17_Mixture_of_Experts_linear_all4.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-17_Mixture_of_Experts_nonlinear.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-15_final_model_padding8_yplus15_uvwT_All_Pr_individuallyfed.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-17_Mixture_of_Experts_nonlinear_softmaxed_3Pr.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-03-17_Mixture_of_Experts_nonlinear_3Pr.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-04-28_unet_new_BN_yplus50_uvw_TauWall.py
#srun python3 -u /home/au567859/DataHandling/notebooks/22-04-05_Mixture_of_Experts_linear_softmaxed_3Pr.py
